spring:
  application:
    name: spring-security-practice

logging:
  level:
    org:
      springframework:
        security: TRACE

#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:certificate.p12
#    key-store-password: password